[project]
name = "foodcoop-shift-calendar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gcsa>=2.5.1",
    "modal>=1.3.1",
    "playwright>=1.51.0",
    "pydantic>=2.11.2",
]
